version: '3.8'

services:
  app:
    image: node:18
    container_name: vite_vue_app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=development
      - VITE_PORT=5678
    command: ["sh", "-c", "yarn install && yarn dev --host 0.0.0.0 --port 5678"]
